const MENU_TOGGLED = 'MENU_TOGGLED';
const ITEM_ADDED = 'ITEM_ADDED';
const INPUT_CHANGED = 'INPUT_CHANGED';
const REMOVE_BUTTON_CLICKED = 'REMOVE_BUTTON_CLICKED';
const RESTORE_BUTTON_CLICKED = 'RESTORE_BUTTON_CLICKED';

export {MENU_TOGGLED, ITEM_ADDED, INPUT_CHANGED, REMOVE_BUTTON_CLICKED, RESTORE_BUTTON_CLICKED};