const BUTTON_CLICKED = "BUTTON_CLICKED";
const ADD_ITEM = "ADD_ITEM";
const INPUT_CHANGED = "INPUT_CHANGED";
const REMOVE_BUTTON_PRESSED = "REMOVE_BUTTON_PRESSED";
const RESTORE_BUTTON_PRESSED = "RESTORE_BUTTON_PRESSED";

export {BUTTON_CLICKED, ADD_ITEM, INPUT_CHANGED, REMOVE_BUTTON_PRESSED, RESTORE_BUTTON_PRESSED};